/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#6e4a00",
        "tertiary-fixed": "#ffdeae",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface-variant": "#3f4945",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#fdba45",
        "surface-container": "#e7f0ec",
        "tertiary": "#503500",
        "outline": "#6f7975",
        "on-tertiary-container": "#fbb843",
        "surface-dim": "#d3dcd8",
        "on-tertiary-fixed-variant": "#604100",
        "secondary": "#9b4422",
        "secondary-container": "#ff9068",
        "on-tertiary-fixed": "#281900",
        "on-primary-container": "#8bd2bb",
        "on-primary": "#ffffff",
        "primary-fixed": "#a9f1d9",
        "surface": "#f3fbf8",
        "surface-variant": "#dce4e1",
        "outline-variant": "#bfc9c3",
        "background": "#f3fbf8",
        "surface-container-highest": "#dce4e1",
        "secondary-fixed-dim": "#ffb59b",
        "primary-fixed-dim": "#8ed4bd",
        "error": "#ba1a1a",
        "on-background": "#151d1b",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#7c2d0d",
        "secondary-fixed": "#ffdbcf",
        "surface-container-low": "#edf6f2",
        "surface-bright": "#f3fbf8",
        "inverse-surface": "#2a3230",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#002018",
        "on-surface": "#151d1b",
        "inverse-on-surface": "#eaf3ef",
        "primary": "#004335",
        "surface-tint": "#206a57",
        "on-secondary-container": "#752807",
        "inverse-primary": "#8ed4bd",
        "primary-container": "#0a5c4a",
        "on-secondary-fixed": "#380d00",
        "on-primary-fixed-variant": "#005140",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "margin": "3rem"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-xl": ["Plus Jakarta Sans"],
        "display-md-mobile": ["Playfair Display"],
        "label-lg": ["Plus Jakarta Sans"],
        "display-md": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Playfair Display"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "body-xl": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "display-md-mobile": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-md": ["44px", { lineHeight: "52px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
